### ISSUE TITLE
Authentication error on Heroku

### ISSUE THREAD

**Issue by sameerf3** [paypal/merchant-sdk-ruby#19]
I am using 2 PayPal sdk for payment in my rails application

 1. paypal-sdk-merchant for payout and
 2. paypal-sdk-rest for collecting payments.

Both these sdks use same configuration file.

Paypal-sdk-rest is working fine, but when I initialize a payout call via paypal-sdk-merchant, it give me an error.

````
[#PayPal::SDK::Merchant::DataTypes::ErrorType:0x007fc0f80c7c70 @ShortMessage="Authentication/Authorization Failed", @LongMessage="You do not have permissions to make this API call", @ErrorCode="10002", @SeverityCode="Error"]
````

While I tested the same code on my development machine and it worked like a charm.

It appears that Heroku is blocking our call to Paypal Merchant SDK.

Since the code is working fine in our development environment, this can be a configuration issue.
I also checked that the Ruby and Paypal SDK version are same in both environments.

````ruby
require 'paypal-sdk-merchant'
vets_list = []
vets_list << {
  :ReceiverEmail => 'someone@example.com',
  :Amount => {
  :currencyID => "USD",
  :value => 1.6
  }
}
@api = PayPal::SDK::Merchant::API.new
@mass_pay = @api.build_mass_pay({
  :ReceiverType => "EmailAddress",
  :MassPayItem => vets_list
})
@mass_pay_response = @api.mass_pay(@mass_pay)
````

**Comment by jziaja** [comment]
> It appears that Heroku is blocking our call to PayPal Merchant SDK.

I don't think that's what's going on here.  The message you're receiving is coming from PayPal and is telling you that the API call you're making isn't allowed because the included credentials don't have permission to make the Payout call.  A few questions regarding your setup that might help shed some light on the situation:

* Was this working previously?
* Does your configuration file stored on Heroku contain the correct credentials for your Classic application?
* Is your Classic application created using a PayPal Premier or Business account?
* Is your Rails application targeting Sandbox or Live?
* Have you verified the credentials are being picked up by your Rails app when the call to PayPal is being made?

Also, I should point out that Payout support was recently added to [paypal-sdk-rest](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/rest/data_types.rb#L966).

**Comment by sameerf3** [comment]
Thanks @jziaja for responding back!
Well I wanted to mass pay using PayPal, couldn't find it in paypal-sdk-rest, so I opted to use merchant-sdk-ruby. **Is there option of mass payment in paypal-sdk-rest?**

Answers to your queries are listed below

* Was this working previously?
  * This is new feature in my application, but I have tested this code on development machine.
* Does your configuration file stored on Heroku contain the correct credentials for your Classic application?
  * Yes they contains correct credentials for Classis application, as I already mentioned that paypal-sdk-rest is working fine.
* Is your Classic application created using a PayPal Premier or Business account?
  * Business Account
* Is your Rails application targeting Sandbox or Live?
  * It is targetting live
* Have you verified the credentials are being picked up by your Rails app when the call to PayPal is being made?
  * Yes it is

**Comment by jziaja** [comment]
> Yes they contains correct credentials for Classis application, as I already mentioned that paypal-sdk-rest is working fine.

paypal-sdk-rest uses your REST application credentials, whereas paypal-sdk-merchant uses Classic application credentials.  Each set of credentials are unrelated to one another and must both be in the configuration file in order for calls using both libraries to work.  Are you saying you have both sets of credentials stored in your configuration file?

> It is targetting live

Have you tried targeting Sandbox?  I'm guessing you'll get the same error, but it'd be good to rule that out.  Also, retrieving information from the logs is much easier for our team to do on Sandbox than on the live system.

> Is there option of mass payment in paypal-sdk-rest?

Yes, mass payment (AKA [Payouts](https://developer.paypal.com/docs/api/#payouts)) support was [added to paypal-sdk-rest just last week](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/CHANGELOG.txt#L5).  Version 1.1.0 or later has Payouts support.  [Samples for making payout calls](https://github.com/paypal/PayPal-Ruby-SDK/tree/master/samples/payouts) are also available.  Since you're working on a new integration, we strongly recommend taking a look at the features available using REST as that is what both our team and PayPal will be supporting and improving upon moving forward.  You will need to enable Payout support on your REST application, but an extra benefit will be that your Rails app will only need one set of credentials instead of two. :)

**Comment by sameerf3** [comment]
OMG!!
Thanks alot @jziaja,
I've been looking here and there for weeks for payout functionality in paypal-sdk-rest. It'll just make my day.
Thanks again
:+1:
