### ISSUE TITLE
Error 100002 (Security Error - Security header is not valid)

### ISSUE THREAD

**Issue by AdamDenoon** [paypal/merchant-sdk-ruby#29]
I am getting the following error when issuing a simple Mass Pay request:

`[#<PayPal::SDK::Merchant::DataTypes::ErrorType:0x007f2ff0ae2280 @ShortMessage="Security error", @LongMessage="Security header is not valid", @ErrorCode="10002", @SeverityCode="Error">] `

After verifying that my SOAP API credentials were correct, I tried switching to certificate-based credentials with no luck, revoked the certificate creds, re-issued signature-based ones, and updated them in my config. I am still getting the same error.

Here is my config for the development environment. I've already verified that the ENV variables are passing correctly.

```
  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: ENV['api_cred_a']

  username: ENV['api_cred_u']
  password: ENV['api_cred_p']
  signature: ENV['api_cred_s']
  sandbox_email_address: ENV['api_cred_e']
```

**Comment by juwlee** [comment]
@AdamDenoon it seems you are trying to call sandbox API. Can you please confirm that you are using your sandbox account credentials?

If you are, in order to narrow down the range of issue, please try `curl` to send a request. You can see samples for [authentication](https://developer.paypal.com/docs/classic/api/NVPAPIOverview/) (under `Specifying Credentials Using cURL` section) and [Mass Pay](https://developer.paypal.com/docs/classic/mass-pay/integration-guide/MassPayUsingAPI/#id101DEJ0100A).

**Comment by AdamDenoon** [comment]
@juwlee I was indeed using the live credentials. I switched it to the default sandbox credentials and it started working. Thanks!

**Comment by juwlee** [comment]
@AdamDenoon Glad it was resolved!
